# XF86 Audio Volume Keys via Wireplumber
#bindl=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
#bindl=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+
#bindl=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume -l 0.0 @DEFAULT_AUDIO_SINK@ 5%-

# XF86 Audio Player Keys via playerctl
bindl=NONE,XF86AudioPlay,spawn,playerctl play-pause
bindl=NONE,XF86AudioPrev,spawn,playerctl prev
bindl=NONE,XF86AudioNext,spawn,playerctl next

# XK86 Moniter Brightness via brightnessctl
#bindl=NONE,XF86MonBrightnessDown,spawn,brightnessctl set 2%-
#bindl=NONE,XF86MonBrightnessUp,spawn,brightnessctl set +2%
