bind=SUPER,space,spawn,qs -c noctalia-shell ipc call launcher toggle
bind=SUPER,s,spawn,qs -c noctalia-shell ipc call controlCenter toggle
bind=SUPER,comma,spawn,qs -c noctalia-shell ipc call settings toggle
bind=NONE,XF86AudioRaiseVolume,spawn,qs -c noctalia-shell ipc call volume increase
bind=NONE,XF86AudioLowerVolume,spawn,qs -c noctalia-shell ipc call volume decrease
bind=NONE,XF86AudioMute,spawn,qs -c noctalia-shell ipc call volume muteOutput
bind=NONE,XF86MonBrightnessUp,spawn,qs -c noctalia-shell ipc call brightness increase
bind=NONE,XF86MonBrightnessDown,spawn,qs -c noctalia-shell ipc call brightness decrease
